# Generated by Django 5.2.8 on 2025-11-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='titulo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
