# Generated by Django 5.2.8 on 2025-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_task_done_remove_task_title_task_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descripcion',
            field=models.CharField(blank=True, null=True, verbose_name='Descripcion de tarea'),
        ),
    ]
