# Generated by Django 5.2.8 on 2025-11-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titulo")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("TERMINADO", "Terminado"),
                        ],
                        default="pendiente",
                        max_length=200,
                        verbose_name="Estatus",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado por:"),
                ),
            ],
        ),
    ]
